FROM node:16

# Create app directory
WORKDIR /app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package.json ./
COPY yarn.lock ./
COPY prisma ./prisma/

# Install app dependencies
RUN npm install

RUN npm i -g prisma@4.11.0

COPY . .

RUN npm run prisma:generate

EXPOSE 3000