-- CreateEnum
CREATE TYPE "VestingStatus" AS ENUM ('INITIALIZED', 'WAITING_APPROVAL', 'WAITING_FUNDS', 'LIVE', 'CREATING', 'CREATED', 'COMPLETED', 'REVOKED', 'APPROVED', 'SUCCESS', 'FAILED');

ALTER TABLE "vesting" ADD COLUMN "status" "VestingStatus" NOT NULL DEFAULT E'INITIALIZED';
