name: Workflow

on:
  pull_request:
    branches: [develop]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Use Node.js 18.16.1
        uses: actions/setup-node@v1
        with:
          node-version: 18.16.1
      - name: cache dependencies
        uses: actions/cache@v2
        with:
          path: 'backend/node_modules'
          key: node_modules-${{ hashFiles('yarn.lock') }}
      - name: Install dependencies
        run: yarn
      - name: Run Linting
        run: yarn lint

  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Use Node.js 18.16.1
        uses: actions/setup-node@v1
        with:
          node-version: 18.16.1
      - name: cache dependencies
        uses: actions/cache@v2
        with:
          path: 'backend/node_modules'
          key: node_modules-${{ hashFiles('yarn.lock') }}
      - name: Install dependencies
        run: yarn
      - name: Run Testing
        run: yarn test
        env:
          NODE_ENV: test
          JWT_ACCESS_SECRET: ${{ secrets.JWT_ACCESS_SECRET }}
          JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
